# Generated by Django 3.2.7 on 2021-10-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart_cartproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
